// DocumentS

// Fetch documents
export const FETCH_DOCUMENTS_SUCCESS = 'FETCH_DOCUMENTS_SUCCESS'
export const FETCH_DOCUMENTS_PENDING = 'FETCH_DOCUMENTS_PENDING'
export const FETCH_DOCUMENTS_REJECTED = 'FETCH_DOCUMENTS_REJECTED'

// Create new document
export const CREATE_DOCUMENT_SUCCESS = 'CREATE_DOCUMENT_SUCCESS'
export const CREATE_DOCUMENT_PENDING = 'CREATE_DOCUMENT_PENDING'
export const CREATE_DOCUMENT_REJECTED = 'CREATE_DOCUMENT_REJECTED'

// Open document
export const OPEN_DOCUMENTS_NEW_TAB_SUCCESS = 'OPEN_DOCUMENTS_NEW_TAB_SUCCESS'
export const OPEN_DOCUMENTS_NEW_TAB_PENDING = 'OPEN_DOCUMENTS_NEW_TAB_PENDING'
export const OPEN_DOCUMENTS_NEW_TAB_REJECTED = 'OPEN_DOCUMENTS_NEW_TAB_REJECTED'

// Update documents
export const UPDATE_DOCUMENTS_SUCCESS = 'UPDATE_DOCUMENTS_SUCCESS'
export const UPDATE_DOCUMENTS_PENDING = 'UPDATE_DOCUMENTS_PENDING'
export const UPDATE_DOCUMENTS_REJECTED = 'UPDATE_DOCUMENTS_REJECTED'


// Document

// Open document
export const OPEN_DOCUMENT_SUCCESS = 'OPEN_DOCUMENTS_SUCCESS'
export const OPEN_DOCUMENT_PENDING = 'OPEN_DOCUMENTS_PENDING'
export const OPEN_DOCUMENT_REJECTED = 'OPEN_DOCUMENTS_REJECTED'

// Save document
export const SAVE_DOCUMENT_SUCCESS = 'SAVE_DOCUMENT_SUCCESS'
export const SAVE_DOCUMENT_PENDING = 'SAVE_DOCUMENT_PENDING'
export const SAVE_DOCUMENT_REJECTED = 'SAVE_DOCUMENT_REJECTED'

// Calculate cells value by formulas
export const CALCULATE_CELLS_VALUE = 'CALCULATE_CELLS_VALUE'
export const CHANGE_CELLS_VALUE = 'CHANGE_CELLS_VALUE'
export const CHANGE_CELLS_SIZE = 'CHANGE_CELLS_SIZE'



// export const GET_DOCUMENT = 'DELETE_DOCUMENT';

export const AUTH = 'AUTH'
export const LOGOUT = 'LOGOUT'
