// Documents

// Fetch documents
export const FETCH_DOCUMENTS_SUCCESS = 'FETCH_DOCUMENTS_SUCCESS';
export const FETCH_DOCUMENTS_PENDING = 'FETCH_DOCUMENTS_PENDING';
export const FETCH_DOCUMENTS_REJECTED = 'FETCH_DOCUMENTS_REJECTED';

// Create new document
export const CREATE_DOCUMENT_SUCCESS = 'CREATE_DOCUMENT_SUCCESS';
export const CREATE_DOCUMENT_PENDING = 'CREATE_DOCUMENT_PENDING';
export const CREATE_DOCUMENT_REJECTED = 'CREATE_DOCUMENT_REJECTED';

// Delete documents
export const DELETE_DOCUMENTS_SUCCESS = 'DELETE_DOCUMENTS_SUCCESS';
export const DELETE_DOCUMENTS_PENDING = 'DELETE_DOCUMENTS_PENDING';
export const DELETE_DOCUMENTS_REJECTED = 'DELETE_DOCUMENTS_REJECTED';


// Document



export const GET_DOCUMENT = 'DELETE_DOCUMENT';

export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';
