// Documents

// Fetch documents
export const FETCH_DOCUMENTS_SUCCESS = 'FETCH_DOCUMENTS_SUCCESS';
export const FETCH_DOCUMENTS_PENDING = 'FETCH_DOCUMENTS_PENDING';
export const FETCH_DOCUMENTS_REJECTED = 'FETCH_DOCUMENTS_REJECTED';

// Fetch recycled documents
export const FETCH_RECYCLED_DOCUMENTS_SUCCESS = 'FETCH_RECYCLED_DOCUMENTS_SUCCESS';
export const FETCH_RECYCLED_DOCUMENTS_PENDING = 'FETCH_RECYCLED_DOCUMENTS_PENDING';
export const FETCH_RECYCLED_DOCUMENTS_REJECTED = 'FETCH_RECYCLED_DOCUMENTS_REJECTED';

// Create new document
export const CREATE_DOCUMENT_SUCCESS = 'CREATE_DOCUMENT_SUCCESS';
export const CREATE_DOCUMENT_PENDING = 'CREATE_DOCUMENT_PENDING';
export const CREATE_DOCUMENT_REJECTED = 'CREATE_DOCUMENT_REJECTED';

// Open document
export const OPEN_DOCUMENTS_NEW_TAB_SUCCESS = 'OPEN_DOCUMENTS_NEW_TAB_SUCCESS';
export const OPEN_DOCUMENTS_NEW_TAB_PENDING = 'OPEN_DOCUMENTS_NEW_TAB_PENDING';
export const OPEN_DOCUMENTS_NEW_TAB_REJECTED = 'OPEN_DOCUMENTS_NEW_TAB_REJECTED';

// Recycle documents
export const RECYCLE_DOCUMENTS_SUCCESS = 'RECYCLE_DOCUMENTS_SUCCESS';
export const RECYCLE_DOCUMENTS_PENDING = 'RECYCLE_DOCUMENTS_PENDING';
export const RECYCLE_DOCUMENTS_REJECTED = 'RECYCLE_DOCUMENTS_REJECTED';

// Restore documents
export const RESTORE_DOCUMENTS_SUCCESS = 'RESTORE_DOCUMENTS_SUCCESS';
export const RESTORE_DOCUMENTS_PENDING = 'RESTORE_DOCUMENTS_PENDING';
export const RESTORE_DOCUMENTS_REJECTED = 'RESTORE_DOCUMENTS_REJECTED';

// Delete documents
export const DELETE_DOCUMENTS_SUCCESS = 'DELETE_DOCUMENTS_SUCCESS';
export const DELETE_DOCUMENTS_PENDING = 'DELETE_DOCUMENTS_PENDING';
export const DELETE_DOCUMENTS_REJECTED = 'DELETE_DOCUMENTS_REJECTED';


// Document

// Open document
export const OPEN_DOCUMENT_SUCCESS = 'OPEN_DOCUMENTS_SUCCESS';
export const OPEN_DOCUMENT_PENDING = 'OPEN_DOCUMENTS_PENDING';
export const OPEN_DOCUMENT_REJECTED = 'OPEN_DOCUMENTS_REJECTED';


export const GET_DOCUMENT = 'DELETE_DOCUMENT';

export const AUTH = 'AUTH';
export const LOGOUT = 'LOGOUT';
